
GET https://localhost:8443/setcookie/6d02205d-e6a2-11ef-a026-a8a15965679f

###
GET http://localhost:1235/users?name=SamuelMedinaBlandon&userPassword=mgee2005


###
GET http://localhost:1235/coments/32ea913f-d64b-11ef-bfa0-a8a15965679f


### Crear un comentario
POST http://localhost:8443/setCookie
Content-Type: application/json

{
  "userNameCookie": "Michael"
}
 
### modificar
PATCH  http://localhost:1235/coments/383981a3-c401-11ef-901f-a8a15965679f
Content-Type: application/json

{
  "name": "La Mejor suegra del mundo mundial",
  "coment": "Ya quiero que mi hija y mi yerno se casen el proximo ano, a incios si es posible"
}

###
DELETE http://localhost:1235/coments/eee398ce-c401-11ef-901f-a8a15965679f
